### ISSUE TITLE
Out of range

### ISSUE THREAD

**Issue by ray27890** [m-byte918/MultiOgar-Edited#1510]
So, I went to start my server and went to play, and when I connect I see this.
| [WARN] User account "Local User" disabled
| [INFO] 0 user records loaded.
| [INFO] 0 IP ban records loaded.
| [INFO] MultiOgar-Edited 1.6.0 - An open source multi-protocol ogar server
| [INFO] WebSocket: ws
(node:19360) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
| [INFO] Started stats server on port 88
| [INFO] Listening on port 4444
| [INFO] Current game mode is Free For All
| [INFO] Added 30 player bots
>  __  __       _ _   _  ___                        _____    _ _ _           _    _   __    ___
 |  \/  |_   _| | |_(_)/ _ \  __ _  __ _ _ __     | ____|__| (_) |_ ___  __| |  / | / /_  / _ \
 | |\/| | | | | | __| | | | |/ _` |/ _` | '__|____|  _| / _` | | __/ _ \/ _` |  | || '_ \| | | |
 | |  | | |_| | | |_| | |_| | (_| | (_| | | |_____| |__| (_| | | ||  __/ (_| |  | || (_) | |_| |
 |_|  |_|\__,_|_|\__|_|\___/ \__, |\__,_|_|       |_____\__,_|_|\__\___|\__,_|  |_(_)___(_)___/
                             |___/
| [FATAL] RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -3155
    at checkInt (internal/buffer.js:58:11)
    at writeU_Int32LE (internal/buffer.js:678:3)
    at Buffer.writeUInt32LE (internal/buffer.js:691:10)
    at BinaryWriter.writeUInt32 (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\packet\BinaryWriter.js:32:18)
    at UpdateNodes.writeUpdateItems5 (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\packet\UpdateNodes.js:116:16)
    at UpdateNodes.build (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\packet\UpdateNodes.js:20:34)
    at PacketHandler.sendPacket (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\PacketHandler.js:314:29)
    at PlayerTracker.sendUpdate (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\PlayerTracker.js:300:19)
    at GameServer.updateClients (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\GameServer.js:435:39)
    at GameServer.mainLoop (C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\src\GameServer.js:602:10)

C:\Users\User1\Desktop\Games\MultiOgar-Edited-1.6.0\MultiOgar-Edited-1.6.0\run>pause
Press any key to continue . . .
Can someone help???

**Comment by Borys64** [comment]
May i know what version of NodeJS you're using?

**Comment by Borys64** [comment]
Closing, inactive.
